# Generated by Django 2.1 on 2018-09-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='关键字')),
                ('value', models.TextField(verbose_name='数据')),
            ],
        ),
        migrations.CreateModel(
            name='InputHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='关键字')),
                ('value', models.TextField(verbose_name='数据')),
            ],
        ),
        migrations.CreateModel(
            name='OutputHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='关键字')),
                ('value', models.TextField(verbose_name='数据')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='名称')),
                ('order', models.IntegerField(verbose_name='顺序')),
            ],
        ),
        migrations.CreateModel(
            name='PageRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(verbose_name='代码相关ID')),
                ('tid', models.IntegerField(verbose_name='任务相关ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='名称')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cviews.Page', verbose_name='页ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('task_progress', models.IntegerField(default=0, verbose_name='进度')),
                ('prid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cviews.PageRow', verbose_name='页行ID')),
            ],
        ),
        migrations.AddField(
            model_name='outputhistory',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cviews.Task', verbose_name='任务ID'),
        ),
        migrations.AddField(
            model_name='inputhistory',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cviews.Task', verbose_name='任务ID'),
        ),
        migrations.AddField(
            model_name='cmdhistory',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cviews.Task', verbose_name='任务ID'),
        ),
    ]
