# Generated by Django 2.1 on 2018-09-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=32, verbose_name='名称')),
                ('code_content', models.TextField(blank=True, max_length=131072, verbose_name='代码')),
                ('order', models.IntegerField(default=1, verbose_name='顺序')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSearchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_keyword', models.CharField(max_length=32, verbose_name='关键字')),
                ('code_description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_date', models.DateField(auto_now=True, verbose_name='最近修改')),
                ('relation_info', models.CharField(blank=True, max_length=256, verbose_name='关联信息')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tar_gz', models.BinaryField(blank=True, max_length=52428800, null=True, verbose_name='ExtraTarGz')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='语言')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=32, verbose_name='标签')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='codesearchinfo',
            name='code_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clibs.Language', verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='codesearchinfo',
            name='tag',
            field=models.ManyToManyField(to='clibs.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='codelib',
            name='search_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clibs.CodeSearchInfo'),
        ),
    ]
