# Generated by Django 2.1 on 2018-09-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clibs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
        migrations.AlterModelOptions(
            name='codelib',
            options={'ordering': ['order'], 'verbose_name': '代码', 'verbose_name_plural': '代码存放库'},
        ),
        migrations.AlterModelOptions(
            name='codesearchinfo',
            options={'verbose_name': '代码搜索记录', 'verbose_name_plural': '代码搜索库'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': '语言', 'verbose_name_plural': '语言集'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签集'},
        ),
        migrations.AddField(
            model_name='codesearchinfo',
            name='extra_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/clibs/%Y/%m/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='codesearchinfo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='codesearchinfo',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最近修改'),
        ),
    ]
