# Generated by Django 2.1 on 2018-09-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clibs', '0002_auto_20180912_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesearchinfo',
            name='extra_file',
        ),
        migrations.AddField(
            model_name='codesearchinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/clibs/%Y/%m/%d', verbose_name='附件'),
        ),
    ]
