# Generated by Django 2.1 on 2018-09-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clibs', '0003_auto_20180913_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesearchinfo',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/clibs/%Y/%m/%d/', verbose_name='附件'),
        ),
    ]
